### ISSUE TITLE
[BUG] WiFi Settings - Search button not there by default, and no way to cancel WiFi connection attempt

### ISSUE THREAD

**Issue by serisman** [luc-github/ESP3D-TFT#20] opened 2023-08-22 01:26 UTC
**Describe the bug**
From the WiFi Settings screen on the TFT UI... The Search button doesn't show up until I interact with one of the textbox inputs and then click back out of them.  Also, if I enter incorrect WiFi SSID or WiFi password, or if there is some other connection issue with the specified WiFi connection attempt, the Please wait... spinner shows up and never goes away (unless I reboot the hardware).  

**To Reproduce**
1. (On TFT) Go to 'Settings'.
2. Click on 'WiFi'.
3. Notice the 'Search' button isn't there.
4. Enter incorrect SSID and/or password.
5. Click out of the textbox input(s), and notice that the 'Search' button is now there.
6. Click on the 'Ok' button, and notice that the Spinner shows up but never goes away and there is no way to get back to the inputs.

**Expected behavior**
I would expect the Search button to show as soon as going to the WiFi settings screen.
I would also expect the Please wait... spinner to have some reasonable timeout and/or have a Cancel button.

**Screenshots**
(can be added if they would be helpful)

**Board used (shouldn't matter, but this is my test board):**
 - MCU: ESP32
 - Name: ESP32-2432S028R (with PSRAM hack)
 - Flash size: 4M

**Comment by luc-github** [comment] 2023-08-22 10:58
Because I cannot duplicate due to lack of hardware I can only guess.
Tthere are 2 possibles root causes of the issue that come to my mind:
1- there is race condition issue which should be solved by putting bsp_patch.h (remove .txt extension which is needed fo github ) in the bsp directory of your config ,  detection is automatic nothing else need to be done to use it.
[bsp_patch.h.txt](https://github.com/luc-github/ESP3D-TFT/files/12407968/bsp_patch.h.txt)
![image](https://github.com/luc-github/ESP3D-TFT/assets/8822552/af1c963e-3d8e-4f0c-b7dc-489e9729418f)

2 - The changes you did in sdkconfig may make the task creation to fail due to low heap
please check the serial log to see if ther is any error and feedback , I will tell you what to change if it is this issue

**Comment by serisman** [comment] 2023-08-22 16:22
After looking at the code more, I don't think these issues have anything to do with my hardware.

I believe the issue with the Search button not showing up has to do with this code:
```
void update_sta_button_scan() {
  std::string mode =
      esp3dTftValues.get_string_value(ESP3DValuesIndex::network_mode);
  if (mode == LV_SYMBOL_WIFI) {
    lv_obj_add_flag(btn_scan, LV_OBJ_FLAG_HIDDEN);
  } else {
    lv_obj_clear_flag(btn_scan, LV_OBJ_FLAG_HIDDEN);
  }
}
```
It appears to only be an issue after a reboot with invalid saved SSID/PW and while it is still trying to connect in the background.  If I disable WiFi or wait for it to default to AP mode, the Search button seems to show up correctly.  Not sure if there is a better way to show/hide the button, or if that is actually working as expected.  Granted, this seems like an edge case that I only got into because I was messing around with this on a WiFi network that won't allow me to connect for some reason.  It just didn't seem all that intuitive when I was clicked around.

The 'Please wait...' spinner issue seems to have to do with this code:
```
void update_sta_button_ok() {
  esp3d_log("Update ok vibility");
  std::string mode =
      esp3dTftValues.get_string_value(ESP3DValuesIndex::network_mode);
  if (!esp3dTftsettings.isValidStringSetting(
          ssid_current.c_str(), ESP3DSettingIndex::esp3d_sta_ssid) ||
      (mode == LV_SYMBOL_STATION_MODE && ssid_ini == ssid_current) ||
      !esp3dTftsettings.isValidStringSetting(
          password_current.c_str(), ESP3DSettingIndex::esp3d_sta_password)) {
    esp3d_log("Ok hide");
    lv_obj_add_flag(btn_ok, LV_OBJ_FLAG_HIDDEN);
#if ESP3D_PATCH_DELAY_REFRESH
    if (sta_screen_delay_refresh_timer) {
      lv_timer_del(sta_screen_delay_refresh_timer);
      sta_screen_delay_refresh_timer = NULL;
    }
    sta_screen_delay_refresh_timer =
        lv_timer_create(sta_screen_delay_refresh_timer_cb, 100, NULL);
#else
    spinnerScreen::hide_spinner();
#endif  // ESP3D_PATCH_DELAY_REFRESH
  } else {
    esp3d_log("Ok visible");
    lv_obj_clear_flag(btn_ok, LV_OBJ_FLAG_HIDDEN);
  }
}
```
If I move the `spinnerScreen::hide_spinner();` logic out of the `if` and down to the bottom of the function, it behaves as expected.    Seems like an edge case that wasn't accounted for previously?

**Comment by luc-github** [comment] 2023-08-22 19:20
it is possible - I did not tested  `invalid ssid at start` yet - I will check tomorrow (3am now and I am not ready to check ^_^)

**Comment by luc-github** [comment] 2023-08-22 19:24
Actually no it is working as expected on my side even with invalid SSID as it start then in AP mode 
So issue is happening when connection is ongoing ?
did you tried the patch ?

**Comment by serisman** [comment] 2023-08-22 19:27
If you are referring to the Search button not always showing up when opening the WiFi Settings screen, then yes, it appears to only happen if I open the screen while the on-boot connection attempt is in progress.  If I wait until it times out and switches to AP mode, it appears to work fine.  Or, if I go disable WiFi before going into that screen, it appears to work fine.

I did try the patch, but I didn't notice much difference with or without it.  I probably need to do more testing and understand what it is trying to fix before knowing if its actually needed.

**Comment by luc-github** [comment] 2023-08-22 19:33
looks like I can duplicate if I rush to wifi when starting ESP doing connection with wrong SSID - so it is like no wifi because it is connecting - but waiting few sec in this state and UI detect AP mode and so it is ok, search button appear
I will try to hide wifi setting if connection is ongoing 

The spinner issue should be fixed by ESP3D_PATCH_DELAY_REFRESH but I cannot reproduce it

if you can give me a step by step reproduction mode would be great

**Comment by luc-github** [comment] 2023-08-22 19:37
and yes there is no way to cancel connection attempt but it automaticaly stop after few sec and move to fallback mode

**Comment by serisman** [comment] 2023-08-22 19:41
Yes, I noticed that it does automatically stop after a few seconds, and the WebUI is still totally fine.  It is just the TFT that seems locked up (because the spinner doesn't get hidden properly and covers up everything else).  My guess is it is because the mode doesn't get changed to LV_SYMBOL_STATION_MODE and therefore the code doesn't try to hide the spinner.  Is there any harm in moving the spinner hide code outside the if in that `update_sta_button_ok` method?

I'll try and come up with more specific steps to reproduce this, but that will have to come later.  I'm busy with actual work at the moment. ;)

**Comment by serisman** [comment] 2023-08-23 02:12
Here are the exact steps I just used to reproduce this.

Pre-Steps:
* The only code changes in play are the sdkconfig and other changes needed to enable PSRAM (and 16MB flash) for my modded ESP32-2432S028R target (I reverted the bsp_patch.h change and other test code changes I made earlier).
  * Here is a comparison to your main repo: https://github.com/luc-github/ESP3D-TFT/compare/main...serisman:ESP3D-TFT:main
* Make sure the flash chip is fully erased / factory default using esptool.py and the `erase_flash` command.
* ESP-IDF Full Clean
* ESP-IDF Build, Flash and Monitor

On the TFT Screen:
* Click on Settings button
* Click on WiFi button
* Click on middle WiFi button
* Click on SSID and enter incorrect (but valid) value
* Click on PW and enter incorrect (but valid) value
* Click on Ok button
* ... Please Wait ... is displayed and never goes away until ESP is rebooted.

Here is the log:
```
[esp3d_tft.cpp:69] begin(): Starting ESP3D-TFT on ESP32_2432S028R 
[esp3d_tft.cpp:71] begin(): Initialising NVS
[bsp.c:65] bsp_init(): Display buffer size: 3200
[bsp.c:68] bsp_init(): Initializing SPI master for display
[spi_bus.c:61] spi_driver_init(): Configuring SPI host SPI2_HOST
[spi_bus.c:62] spi_driver_init(): MISO pin: 12, MOSI pin: 13, SCLK pin: 14, IO2/WP pin: -1, IO3/HD pin: -1
[spi_bus.c:65] spi_driver_init(): Max transfer size: 6400 (bytes)
[spi_bus.c:76] spi_driver_init(): Initializing SPI bus...
[bsp.c:73] bsp_init(): Initializing display controller
[disp_spi.c:114] disp_spi_add_device_with_speed(): Adding SPI device
[disp_spi.c:115] disp_spi_add_device_with_speed(): Clock speed: 40000000Hz, mode: 0, CS pin: 15
[ili9341.c:97] ili9341_init(): Initialization.
[ili9341.c:195] ili9341_set_orientation(): Display orientation: LANDSCAPE_INVERTED
[ili9341.c:201] ili9341_set_orientation(): 0x36 command value: 0xE8
[esp_lcd_backlight.c:84] disp_backlight_set(): Setting LCD backlight: 100%
[bsp.c:97] bsp_init(): Initializing touch controller
[xpt2046.c:66] xpt2046_init(): XPT2046 Initialization
[xpt2046.c:81] xpt2046_init(): Pins configuration (Miso)
[xpt2046.c:92] xpt2046_init(): Pins configuration (Mosi)
[bsp.c:104] bsp_init(): Setup Lvgl
[esp3d_tft.cpp:83] begin(): NVS is valid
[esp3d_tft.cpp:87] begin(): NVS Setting version is ESP3D_TFT-V1.0.0
[esp_flash_littleFs.cpp:68] mount(): Flash Filesystem mounted
[esp_flash_littleFs.cpp:125] getSpaceInfo(): Total:8323072, Used:8192, Free:8314880
[esp_flash_littleFs.cpp:75] mount(): Total:7.94 MB
[esp_flash_littleFs.cpp:76] mount(): Used:8.00 KB
[esp_flash_littleFs.cpp:77] mount(): Free:7.93 MB
[esp_sd_spi.cpp:115] begin(): Initializing SD card
[esp_sd_spi.cpp:122] begin(): Configuring SPI host SPI3_HOST
[esp_sd_spi.cpp:123] begin(): MISO pin: 19, MOSI pin: 23, SCLK pin: 18, IO2/WP pin: -1, IO3/HD pin: -1
[esp_sd_spi.cpp:128] begin(): Max transfer size: 4000 (bytes)
[esp3d_translation_service.cpp:58] begin(): Starting Translation Service
[esp3d_translation_service.cpp:76] begin(): Using default language pack: ???
[esp3d_rendering_client.cpp:81] begin(): Created Rendering Task
[esp3d_rendering_client.cpp:82] begin(): Rendering client started
[esp3d_tft_ui.cpp:113] begin(): Created UI Task
[esp3d_update_service.cpp:315] begin(): Starting Update Service
[esp3d_update_service.cpp:288] canUpdate(): Running partition subtype 16 at offset 0x10000
[esp3d_update_service.cpp:291] canUpdate(): Running firmware version: a1c9a1b-dirty
[esp3d_update_service.cpp:297] canUpdate(): Update partition subtype 17 at offset 0x410000
[esp_sd_spi.cpp:78] mount(): CS pin 5, host_id 2 , Max Freq 20000
[esp_sd_spi.cpp:90] mount(): Mounting filesystem cd:-1, wp:-1
[esp_sd_spi.cpp:104] mount(): Filesystem mounted
[esp3d_sd.cpp:50] accessFS(): Access SD
[esp3d_update_service.cpp:355] begin(): No Fw update on SD
[esp3d_sd.cpp:57] releaseFS(): Release SD
[esp3d_tft_stream.cpp:100] begin(): Created Stream Task
[esp3d_gcode_host_service.cpp:195] begin(): Created GCode Host Task
[esp3d_gcode_host_service.cpp:196] begin(): GCode Host service started
[esp3d_commands.cpp:1072] getOutputClie[esp3d_serial_client.cpp:179] begin(): Created Serial Task
[esp3d_serial_client.cpp:180] begin(): Serial client started
[esp3d_tft_network.cpp:80] begin(): Free mem 4271896
[esp3d_tft_network.cpp:87] begin(): Created Network Task
[esp3d_tft_network.cpp:88] begin(): Free mem 4267364
[esp3d_tft_network.cpp:54] networkTask(): Init Netif and network event loop
[esp3d_network.cpp:207] begin(): Free mem 4263420
[esp3d_values.cpp:67] set_string_value(): Setting String value  for 18
[esp3d_values.cpp:67] set_string_value(): Setting String value x for 17
[esp3d_values.cpp:67] set_string_value(): Setting String value Not connected for 0
[status_screen.cpp:52] status_list_cb(): status_list_cb size is 0
[status_screen.cpp:60] status_list_cb(): status_list pushing Not connected now size is 1
[status_screen.cpp:66] status_list_cb(): No refresh needed
[esp3d_network.cpp:751] setMode(): Current mode is 0, and ask for 3
[esp3d_network.cpp:635] stopNoRadioMode(): Stop No Radio Mode
[esp3d_network.cpp:654] startConfigMode(): Init Config Mode
[esp3d_values.cpp:67] set_string_value(): Setting String value Set as Access Point for 0
[status_screen.cpp:52] status_list_cb(): status_list_cb size is 1
[status_screen.cpp:60] status_list_cb(): status_list pushing Set as Access Point now size is 2
[status_screen.cpp:66] status_list_cb(): No refresh needed
[esp3d_network.cpp:503] startApMode(): Init AP Mode
[esp3d_network.cpp:504] startApMode(): Free mem 4263204
[esp3d_network.cpp:506] startApMode(): Create default ap service
[esp3d_network.cpp:510] startApMode(): Free mem 4177424
[esp3d_network.cpp:515] startApMode(): Configure AP settings
[esp3d_network.cpp:518] startApMode(): Register wifi handler
[esp3d_network.cpp:528] startApMode(): Got  AP settings: SSID:<esp3dtft> password:<12345678> channel:<2>
[esp3d_network.cpp:546] startApMode(): Setup IP and DHCP range
[esp3d_network.cpp:556] startApMode(): set AP mode
[esp3d_network.cpp:558] startApMode(): Set configuration
[esp3d_network.cpp:560] startApMode(): Start wifi
[esp3d_network.cpp:582] startApMode(): wifi_init_softap done. - SSID:esp3dtft - channel:2
[esp3d_network.cpp:584] startApMode(): AP IP: 192.168.0.1
[esp3d_network.cpp:585] startApMode(): AP GW: 192.168.0.1
[esp3d_network.cpp:586] startApMode(): AP NETMASK: 255.255.255.0
[esp3d_commands.cpp:421] dispatch(): Dispatch message origin 10 to client 11 , size: 82,  type: 3
[esp3d_commands.cpp:421] dispatch(): Dispatch message origin 10 to client 7 , size: 82,  type: 3
[esp3d_commands.cpp:457] dispatch(): esp3dWsDataService not started for message size  82
[esp3d_commands.cpp:639] dispatch(): Send msg failed
[esp3d_commands.cpp:421] dispatch(): Dispatch message origin 10 to client 4 , size: 82,  type: 3
[esp3d_commands.cpp:469] dispatch(): esp3dSocketServer not started for message size  82
[esp3d_commands.cpp:639] dispatch(): Send msg failed
[esp3d_commands.cpp:421] dispatch(): Dispatch message origin 10 to client 6 , size: 82,  type: 3
[esp3d_commands.cpp:447] dispatch(): esp3dWsWebUiService not started for message size  82
[esp3d_commands.cpp:639] dispatch(): Send msg failed
[esp3d_values.cpp:67] set_string_value(): Setting String value + for 17
[esp3d_network_services.cpp:55] begin(): Starting Services
[esp3d_http_service.cpp:172] begin(): Starting Http Service
[esp3d_http_service.cpp:202] begin(): Starting server on port: '80'
[esp3d_http_service.cpp:206] begin(): Registering URI handlers
[esp3d_ws_service.cpp:175] begin(): Starting Ws Service
[esp3d_ws_service.cpp:208] begin(): Ws Service Started type:2
[esp3d_ws_service.cpp:175] begin(): Starting Ws Service
[esp3d_ws_service.cpp:208] begin(): Ws Service Started type:3
[esp3d_notifications_service.cpp:40] begin(): Start notification service
[main_screen.cpp:506] main_screen(): Main screen creation
[esp3d_mdns.cpp:169] begin(): mDNS Service started
[esp3d_ssdp.cpp:97] begin(): SSDP Service started
[esp3d_socket_server.cpp:113] startSocketServer(): Socket marked as non blocking
[esp3d_socket_server.cpp:115] startSocketServer(): Socket created
[esp3d_socket_server.cpp:125] startSocketServer(): Socket bound, port 23
[esp3d_socket_server.cpp:400] begin(): Created Socket Task
[esp3d_socket_server.cpp:401] begin(): Socket Server started port 23
[esp3d_values.cpp:67] set_string_value(): Setting String value  for 18
[main_screen.cpp:465] event_button_menu_handler(): Menu Clicked
[menu_screen.cpp:197] menu_screen(): menu screen creation
[menu_screen.cpp:142] event_button_wifi_handler(): wifi Clicked
[wifi_screen.cpp:162] wifi_screen(): Wifi screen creation
[wifi_screen.cpp:133] event_button_sta_handler(): STA Clicked
[sta_screen.cpp:418] sta_screen(): STA screen creation
[sta_screen.cpp:439] sta_screen(): width_label 16
[sta_screen.cpp:248] update_sta_button_ok(): Update ok vibility
[sta_screen.cpp:256] update_sta_button_ok(): Ok hide
[sta_screen.cpp:275] update_button_save(): Update save vibility
[sta_screen.cpp:278] update_button_save(): Save hide
[sta_screen.cpp:248] update_sta_button_ok(): Update ok vibility
[sta_screen.cpp:256] update_sta_button_ok(): Ok hide
[sta_screen.cpp:275] update_button_save(): Update save vibility
[sta_screen.cpp:278] update_button_save(): Save hide
[sta_screen.cpp:358] sta_ta_event_cb(): Value changed, SSID:  > vsdhgj
[sta_screen.cpp:248] update_sta_button_ok(): Update ok vibility
[sta_screen.cpp:269] update_sta_button_ok(): Ok visible
[sta_screen.cpp:275] update_button_save(): Update save vibility
[sta_screen.cpp:286] update_button_save(): Save visible
[sta_screen.cpp:362] sta_ta_event_cb(): Value changed, PASSWORD:  > g
[sta_screen.cpp:248] update_sta_button_ok(): Update ok vibility
[sta_screen.cpp:256] update_sta_button_ok(): Ok hide
[sta_screen.cpp:275] update_button_save(): Update save vibility
[sta_screen.cpp:286] update_button_save(): Save visible
[sta_screen.cpp:362] sta_ta_event_cb(): Value changed, PASSWORD:  > ghhdgbsj
[sta_screen.cpp:248] update_sta_button_ok(): Update ok vibility
[sta_screen.cpp:269] update_sta_button_ok(): Ok visible
[sta_screen.cpp:275] update_button_save(): Update save vibility
[sta_screen.cpp:286] update_button_save(): Save visible
[sta_screen.cpp:248] update_sta_button_ok(): Update ok vibility
[sta_screen.cpp:269] update_sta_button_ok(): Ok visible
[sta_screen.cpp:275] update_button_save(): Update save vibility
[sta_screen.cpp:286] update_button_save(): Save visible
[sta_screen.cpp:385] sta_event_button_ok_handler(): Ok Clicked
[sta_screen.cpp:386] sta_event_button_ok_handler(): ssid: vsdhgj, password:ghhdgbsj
[esp3d_settings.cpp:791] writeString(): write setting 6 : (6 bytes) vsdhgj
[esp3d_settings.cpp:806] writeString(): Write success
[esp3d_settings.cpp:791] writeString(): write setting 7 : (8 bytes) ghhdgbsj
[esp3d_settings.cpp:806] writeString(): Write success
[sta_screen.cpp:275] update_button_save(): Update save vibility
[sta_screen.cpp:278] update_button_save(): Save hide
[esp3d_translation_service.cpp:188] translate(): Key index: 23 is found in translation and text is Please wait...
[esp3d_network.cpp:239] setModeAsync(): Enabling async mode to 1
[esp3d_network.cpp:254] handle(): Asking for change to 1
[esp3d_network.cpp:751] setMode(): Current mode is 3, and ask for 1
[esp3d_network.cpp:731] stopConfigMode(): Stop Config Mode
[esp3d_network_services.cpp:83] end(): Stop Services
[esp3d_socket_server.cpp:527] end(): End socket server
[esp3d_socket_server.cpp:574] closeAllClients(): Socket server closing all clients
[esp3d_socket_server.cpp:533] end(): Clearing queue Rx messages
[esp3d_socket_server.cpp:535] end(): Clearing queue Tx messages
[esp3d_socket_server.cpp:544] end(): Stop telnet server
[esp3d_socket_server.cpp:558] end(): Socket server data cleared
[esp3d_socket_server.cpp:569] end(): Socket server buffer cleared
[esp3d_http_service.cpp:394] end(): Stop Http Service
[esp3d_ws_service.cpp:155] end(): Stop Ws Service 2
[esp3d_ws_service.cpp:155] end(): Stop Ws Service 3
[esp3d_mdns.cpp:176] end(): Stop mDNS service
[esp3d_ssdp.cpp:106] end(): Stop SSDP service
[esp3d_network.cpp:705] stopApMode(): Stop AP Mode
[esp3d_network.cpp:715] stopApMode(): Stop DHCP
[esp3d_network.cpp:717] stopApMode(): Destroy default wifi AP
[esp3d_values.cpp:67] set_string_value(): Setting String value Connecting for 0
[status_screen.cpp:52] status_list_cb(): status_list_cb size is 2
[status_screen.cpp:60] status_list_cb(): status_list pushing Connecting now size is 3
[status_screen.cpp:66] status_list_cb(): No refresh needed
[esp3d_network.cpp:320] startStaMode(): Init STA Mode
[esp3d_network.cpp:335] startStaMode(): Free mem 4129196
[esp3d_network.cpp:336] startStaMode(): Create default sta service
[esp3d_network.cpp:340] startStaMode(): Free mem 4129196
[esp3d_network.cpp:345] startStaMode(): Register wifi handler
[esp3d_network.cpp:353] startStaMode(): Configure STA settings
[esp3d_network.cpp:359] startStaMode(): Got  STA settings: SSID:<vsdhgj> password:<ghhdgbsj> ip mode :<DHCP>
[esp3d_network.cpp:398] startStaMode(): Use DHCP
[esp3d_network.cpp:402] startStaMode(): Dhcp client started
[esp3d_commands.cpp:421] dispatch(): Dispatch message origin 10 to client 11 , size: 21,  type: 3
[esp3d_commands.cpp:421] dispatch(): Dispatch message origin 10 to client 7 , size: 21,  type: 3
[esp3d_commands.cpp:457] dispatch(): esp3dWsDataService not started for message size  21
[esp3d_commands.cpp:639] dispatch(): Send msg failed
[esp3d_commands.cpp:421] dispatch(): Dispatch message origin 10 to client 4 , size: 21,  type: 3
[esp3d_commands.cpp:469] dispatch(): esp3dSocketServer not started for message size  21
[esp3d_commands.cpp:639] dispatch(): Send msg failed
[esp3d_commands.cpp:421] dispatch(): Dispatch message origin 10 to client 6 , size: 21,  type: 3
[esp3d_commands.cpp:447] dispatch(): esp3dWsWebUiService not started for message size  21
[esp3d_commands.cpp:639] dispatch(): Send msg failed
[esp3d_network.cpp:81] wifi_sta_event_handler(): Try to connect to the AP
[esp3d_values.cpp:67] set_string_value(): Setting String value + for 17
[esp3d_network.cpp:85] wifi_sta_event_handler(): Success connecting to the AP
[esp3d_network.cpp:96] wifi_sta_event_handler(): Disconnected
[esp3d_values.cpp:67] set_string_value(): Setting String value x for 17
[esp3d_network.cpp:99] wifi_sta_event_handler(): retry to connect to the AP 0
[esp3d_network.cpp:103] wifi_sta_event_handler(): Success connecting to the AP
[esp3d_values.cpp:67] set_string_value(): Setting String value + for 17
[esp3d_network.cpp:96] wifi_sta_event_handler(): Disconnected
[esp3d_values.cpp:67] set_string_value(): Setting String value x for 17
[esp3d_network.cpp:99] wifi_sta_event_handler(): retry to connect to the AP 1
[esp3d_network.cpp:103] wifi_sta_event_handler(): Success connecting to the AP
[esp3d_values.cpp:67] set_string_value(): Setting String value + for 17
[esp3d_network.cpp:96] wifi_sta_event_handler(): Disconnected
[esp3d_values.cpp:67] set_string_value(): Setting String value x for 17
[esp3d_network.cpp:99] wifi_sta_event_handler(): retry to connect to the AP 2
[esp3d_network.cpp:103] wifi_sta_event_handler(): Success connecting to the AP
[esp3d_values.cpp:67] set_string_value(): Setting String value + for 17
[esp3d_network.cpp:96] wifi_sta_event_handler(): Disconnected
[esp3d_values.cpp:67] set_string_value(): Setting String value x for 17
[esp3d_network.cpp:99] wifi_sta_event_handler(): retry to connect to the AP 3
[esp3d_network.cpp:103] wifi_sta_event_handler(): Success connecting to the AP
[esp3d_values.cpp:67] set_string_value(): Setting String value + for 17
[esp3d_network.cpp:96] wifi_sta_event_handler(): Disconnected
[esp3d_values.cpp:67] set_string_value(): Setting String value x for 17
[esp3d_network.cpp:99] wifi_sta_event_handler(): retry to connect to the AP 4
[esp3d_network.cpp:103] wifi_sta_event_handler(): Success connecting to the AP
[esp3d_values.cpp:67] set_string_value(): Setting String value + for 17
[esp3d_network.cpp:96] wifi_sta_event_handler(): Disconnected
[esp3d_values.cpp:67] set_string_value(): Setting String value x for 17
[esp3d_network.cpp:99] wifi_sta_event_handler(): retry to connect to the AP 5
[esp3d_network.cpp:103] wifi_sta_event_handler(): Success connecting to the AP
[esp3d_values.cpp:67] set_string_value(): Setting String value + for 17
[esp3d_network.cpp:96] wifi_sta_event_handler(): Disconnected
[esp3d_values.cpp:67] set_string_value(): Setting String value x for 17
[esp3d_network.cpp:99] wifi_sta_event_handler(): retry to connect to the AP 6
[esp3d_network.cpp:103] wifi_sta_event_handler(): Success connecting to the AP
[esp3d_values.cpp:67] set_string_value(): Setting String value + for 17
[esp3d_network.cpp:96] wifi_sta_event_handler(): Disconnected
[esp3d_values.cpp:67] set_string_value(): Setting String value x for 17
[esp3d_network.cpp:99] wifi_sta_event_handler(): retry to connect to the AP 7
[esp3d_network.cpp:103] wifi_sta_event_handler(): Success connecting to the AP
[esp3d_values.cpp:67] set_string_value(): Setting String value + for 17
[esp3d_network.cpp:96] wifi_sta_event_handler(): Disconnected
[esp3d_values.cpp:67] set_string_value(): Setting String value x for 17
[esp3d_network.cpp:99] wifi_sta_event_handler(): retry to connect to the AP 8
[esp3d_network.cpp:103] wifi_sta_event_handler(): Success connecting to the AP
[esp3d_values.cpp:67] set_string_value(): Setting String value + for 17
[esp3d_network.cpp:96] wifi_sta_event_handler(): Disconnected
[esp3d_values.cpp:67] set_string_value(): Setting String value x for 17
[esp3d_network.cpp:99] wifi_sta_event_handler(): retry to connect to the AP 9
[esp3d_network.cpp:103] wifi_sta_event_handler(): Success connecting to the AP
[esp3d_values.cpp:67] set_string_value(): Setting String value + for 17
[esp3d_network.cpp:96] wifi_sta_event_handler(): Disconnected
[esp3d_values.cpp:67] set_string_value(): Setting String value x for 17
[esp3d_network.cpp:114] wifi_sta_event_handler(): retries to connect to the AP failed
[esp3d_values.cpp:67] set_string_value(): Setting String value x for 17
[esp3d_network.cpp:455] startStaMode(): Failed to connect to SSID: vsdhgj, password: ghhdgbsj
[esp3d_values.cpp:67] set_string_value(): Setting String value Connect to vsdhgj failed for 0
[status_screen.cpp:52] status_list_cb(): status_list_cb size is 3
[status_screen.cpp:60] status_list_cb(): status_list pushing Connect to vsdhgj failed now size is 4
[status_screen.cpp:66] status_list_cb(): No refresh needed
[esp3d_commands.cpp:421] dispatch(): Dispatch message origin 10 to client 11 , size: 25,  type: 3
[esp3d_commands.cpp:421] dispatch(): Dispatch message origin 10 to client 7 , size: 25,  type: 3
[esp3d_commands.cpp:457] dispatch(): esp3dWsDataService not started for message size  25
[esp3d_commands.cpp:639] dispatch(): Send msg failed
[esp3d_commands.cpp:421] dispatch(): Dispatch message origin 10 to client 4 , size: 25,  type: 3
[esp3d_commands.cpp:469] dispatch(): esp3dSocketServer not started for message size  25
[esp3d_commands.cpp:639] dispatch(): Send msg failed
[esp3d_commands.cpp:421] dispatch(): Dispatch message origin 10 to client 6 , size: 25,  type: 3
[esp3d_commands.cpp:447] dispatch(): esp3dWsWebUiService not started for message size  25
[esp3d_commands.cpp:639] dispatch(): Send msg failed
[esp3d_network.cpp:751] setMode(): Current mode is 1, and ask for 3
[esp3d_network.cpp:663] stopStaMode(): Stop STA Mode
[esp3d_network.cpp:670] stopStaMode(): Clear xEventGroupBits
[esp3d_network.cpp:686] stopStaMode(): Stop DHCP Client
[esp3d_network.cpp:654] startConfigMode(): Init Config Mode
[esp3d_values.cpp:67] set_string_value(): Setting String value Set as Access Point for 0
[status_screen.cpp:52] status_list_cb(): status_list_cb size is 4
[status_screen.cpp:60] status_list_cb(): status_list pushing Set as Access Point now size is 5
[status_screen.cpp:66] status_list_cb(): No refresh needed
[esp3d_network.cpp:503] startApMode(): Init AP Mode
[esp3d_network.cpp:504] startApMode(): Free mem 4129196
[esp3d_network.cpp:506] startApMode(): Create default ap service
[esp3d_network.cpp:510] startApMode(): Free mem 4129196
[esp3d_network.cpp:515] startApMode(): Configure AP settings
[esp3d_network.cpp:518] startApMode(): Register wifi handler
[esp3d_network.cpp:528] startApMode(): Got  AP settings: SSID:<esp3dtft> password:<12345678> channel:<2>
[esp3d_network.cpp:546] startApMode(): Setup IP and DHCP range
[esp3d_network.cpp:556] startApMode(): set AP mode
[esp3d_network.cpp:558] startApMode(): Set configuration
[esp3d_network.cpp:560] startApMode(): Start wifi
[esp3d_network.cpp:582] startApMode(): wifi_init_softap done. - SSID:esp3dtft - channel:2
[esp3d_network.cpp:584] startApMode(): AP IP: 192.168.0.1
[esp3d_network.cpp:585] startApMode(): AP GW: 192.168.0.1
[esp3d_network.cpp:586] startApMode(): AP NETMASK: 255.255.255.0
[esp3d_commands.cpp:421] dispatch(): Dispatch message origin 10 to client 11 , size: 82,  type: 3
[esp3d_commands.cpp:421] dispatch(): Dispatch message origin 10 to client 7 , size: 82,  type: 3
[esp3d_commands.cpp:457] dispatch(): esp3dWsDataService not started for message size  82
[esp3d_commands.cpp:639] dispatch(): Send msg failed
[esp3d_commands.cpp:421] dispatch(): Dispatch message origin 10 to client 4 , size: 82,  type: 3
[esp3d_commands.cpp:469] dispatch(): esp3dSocketServer not started for message size  82
[esp3d_commands.cpp:639] dispatch(): Send msg failed
[esp3d_commands.cpp:421] dispatch(): Dispatch message origin 10 to client 6 , size: 82,  type: 3
[esp3d_commands.cpp:447] dispatch(): esp3dWsWebUiService not started for message size  82
[esp3d_commands.cpp:639] dispatch(): Send msg failed
[esp3d_values.cpp:67] set_string_value(): Setting String value + for 17
[esp3d_network_services.cpp:55] begin(): Starting Services
[esp3d_http_service.cpp:172] begin(): Starting Http Service
[esp3d_http_service.cpp:202] begin(): Starting server on port: '80'
[esp3d_http_service.cpp:206] begin(): Registering URI handlers
[esp3d_ws_service.cpp:175] begin(): Starting Ws Service
[esp3d_ws_service.cpp:208] begin(): Ws Service Started type:2
[esp3d_ws_service.cpp:175] begin(): Starting Ws Service
[esp3d_ws_service.cpp:208] begin(): Ws Service Started type:3
[esp3d_notifications_service.cpp:40] begin(): Start notification service
[esp3d_mdns.cpp:169] begin(): mDNS Service started
[esp3d_ssdp.cpp:97] begin(): SSDP Service started
[esp3d_socket_server.cpp:400] begin(): Created Socket Task
[esp3d_socket_server.cpp:401] begin(): Socket Server started port 23
[esp3d_values.cpp:67] set_string_value(): Setting String value  for 18
[sta_screen.cpp:248] update_sta_button_ok(): Update ok vibility
[sta_screen.cpp:269] update_sta_button_ok(): Ok visible
[esp3d_socket_server.cpp:113] startSocketServer(): Socket marked as non blocking
[esp3d_socket_server.cpp:115] startSocketServer(): Socket created
[esp3d_socket_server.cpp:125] startSocketServer(): Socket bound, port 23
```

**Comment by serisman** [comment] 2023-08-23 02:18
I just re-added the bsp_patch.h and get identical behavior.

**Comment by luc-github** [comment] 2023-08-23 02:19
I have found that even AP SSID is wrong the WiFi raise event connection success then disconnect - which may lead to race condition - so I update connection state only when starting network services 
In addition of that I have added a spinner that block the access to wifi setting when state is not connected  

I am still on it now I have your repro steps -  issue happen when you are in AP mode first and now I can reproduce it - I will fix it now I see it

**Comment by serisman** [comment] 2023-08-23 02:24
By the way, this bug is no where near as important as progress on the gcode parsing and other unfinished features.  I mainly just wanted to record some of what I noticed that felt weird with some edge cases I ran into.

**Comment by luc-github** [comment] 2023-08-23 02:25
ESP32 SDK  has not really been tuned the one no PSRAM and the rotrix I have is dead 
Yes I suggest to use the values of S3 as they are suposed to be the tested references

**Comment by serisman** [comment] 2023-08-23 02:26
Which S3?  Or, are they all basically the same at this point?

**Comment by luc-github** [comment] 2023-08-23 02:26
Na, it is a bug, and it will bother me until I fix it, I won't be able to focus on another subject especially now I can reproduce it, it is fine no worry should be done soon

**Comment by luc-github** [comment] 2023-08-23 02:27
Yes I hope so - I update each one each time I modify my working one

**Comment by luc-github** [comment] 2023-08-23 04:34
I think I have solved issue but it now raise a new one -  some bg task failed to be created (e.g: scan) and I am pretty sure it is some setting in sdkconfig - I am investigating 
Also be noted : scan button won't appear in No WiFi mode - because need to start all wifi lib without starting network services to do that and then stop wifi again once scan is done, which is not working well yet - current limitation is scan button only appear in sta/ap mode
feel free to have a look if your issue is solved now or when I have solved the task creation issue

**Comment by serisman** [comment] 2023-08-23 05:06
I did some quick testing, and my original issue with the spinner that never goes away is solved!

**Comment by luc-github** [comment] 2023-08-23 11:54
Ok I have reviewed all screen I have in hand and seems ok - I did not updated ESP32 custom/ ESP32-S3 custom sdkconfig because several other settings may be needed depending the board used
For ESP32_2432S028R original does not have PSRAM so there is no need , for moded version, feel free to create a new directory `ESP32_2432S028R_mod` with all necessary change - it will be used in CMakelists.txt when pushed , I will do the updatefor this part

**Comment by luc-github** [comment] 2023-08-23 11:54
So if ok on your side now - I close ticket

**Closed by luc-github** 2023-08-23 11:54 UTC
Labels: bug, Screen, WiFi
